
  # For modes: STANDARD, STORAGE, AUTH
  s3.gateway.rs:
    image: ${S3_GATEWAY_RS_IMAGE}
    container_name: ${S3_GATEWAY_RS_CONTAINER_NAME}
    hostname: ${S3_GATEWAY_RS_HOSTNAME}
    depends_on:
      s3.storage:
        condition: service_healthy
    restart: ${GENERIC_RESTART}
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/7878; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      S3_URL: ${S3_GATEWAY_RS_S3_URL}
      API_KEY: ${S3_GATEWAY_RS_API_KEY}
      SECRET_KEY: ${S3_GATEWAY_RS_SECRET_KEY}
      BUCKET_NAME: ${S3_GATEWAY_RS_BUCKET_NAME}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    # ports:
    #   - ${S3_GATEWAY_RS_EXTERNAL_PORT}:${S3_GATEWAY_RS_PORT}
    volumes:
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
