
  # For modes: STANDARD, VUE, STORAGE, CACHE, AUTH
  vue.ui:
    image: ${VUE_UI_IMAGE}
    container_name: ${VUE_UI_CONTAINER_NAME}
    hostname: ${VUE_UI_HOSTNAME}
    restart: ${GENERIC_RESTART}
    environment:
      API_URL: ${VUE_UI_API_URL}
      PUBLIC_PATH: ${VUE_UI_PUBLIC_PATH}
    # ports:
    #   - ${VUE_UI_EXTERNAL_PORT}:80
    volumes:
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
