
  # For modes: CACHE, AUTH
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    hostname: ${ZOOKEEPER_HOSTNAME}
    healthcheck:
      test: echo srvr | nc localhost 2181 | grep Mode  # get info from zookeeper server
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    # ports:
    #   - ${ZOOKEEPER_PORT}:2181
    volumes:
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
