
  # For modes: STANDARD, CACHE, AUTH
  dictionary-rs:
    image: ${DICTIONARY_RS_IMAGE}
    container_name: ${DICTIONARY_RS_CONTAINER_NAME}
    hostname: ${DICTIONARY_RS_HOSTNAME}
    depends_on:
      opensearch-node:
        condition: service_healthy
    restart: ${GENERIC_RESTART}
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/${DICTIONARY_RS_PORT}; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      PORT: ${DICTIONARY_RS_PORT}
      KAFKA_HOST: ${DICTIONARY_RS_KAFKA_HOST}
      OPENSEARCH_URL: ${DICTIONARY_RS_OPENSEARCH_URL}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    # ports:
    #   - ${DICTIONARY_RS_EXTERNAL_PORT}:${DICTIONARY_RS_PORT}
    volumes:
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
