
  # For modes: STANDARD
  ui.gateway:
    image: ${NGINX_UI_GATEWAY_IMAGE}
    container_name: ${NGINX_UI_GATEWAY_CONTAINER_NAME}
    hostname: ${NGINX_UI_GATEWAY_HOSTNAME}
    depends_on:
      grpc.proxy:
        condition: service_healthy
      # vue.ui:
      #   condition: service_healthy
      dictionary.rs:
        condition: service_started
      adempiere.site:
        condition: service_started
    ports:
      - ${NGINX_UI_GATEWAY_HTTP_EXTERNAL_PORT}:${NGINX_UI_GATEWAY_HTTP_INTERNAL_PORT}
      # Remember to open port 443 on host if you want to use HTTPS protocol
      - ${NGINX_UI_GATEWAY_HTTPS_EXTERNAL_PORT}:${NGINX_UI_GATEWAY_HTTPS_INTERNAL_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/upstreams/:/etc/nginx/api_upstreams_conf.d
      - ./nginx/api/:/etc/nginx/api_conf.d
      - ./nginx/gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./nginx/api_json_errors.conf:/etc/nginx/api_json_errors.conf

      # Certificate generated by Letsencypt on the Host. Only fullchain.pem and privkey.pem are needed.
      # Replace YOUR_DOMAINNAME with the DNS value you have acquired the Certificate for on the Host
      - /etc/letsencrypt/live/YOUR_DOMAINNAME/fullchain.pem:/etc/letsencrypt/live/YOUR_DOMAINNAME/fullchain.pem
      - /etc/letsencrypt/live/YOUR_DOMAINNAME/privkey.pem:/etc/letsencrypt/live/YOUR_DOMAINNAME/privkey.pem
      # Diffie-Hellman to secure Certificate transport. It must also be generated on the Host.
      # Command to generate: openssl dhparam -out /etc/nginx/dhparam.pem 4096
      - /etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem

      #- ./keys/api_keys.conf:/etc/nginx/api_keys.conf
      # time zone
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
