openapi: 3.0.0
info:
  title: Notice_management
  version: 1.0.0
servers:
  - url: http://{{host}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /notice-management/notices/users:
    get:
      tags:
        - default
      summary: ListUsers
      description: >-
        **Endpoint**: GET /notice-management


        **Description**: Returns ListNotices


        **FULL URL**:
        [http://api.adempiere.io](http://api.adempiere.io/api)/notice-management/notices/users


        **Method**: GET


        **Application Example**


        ``` bash

        curl --location
        'http://api.adempiere.io/notice-management/notices/users' \

        --header 'Authorization: Bearer
        eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTQ2IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE3MTA2Mjg3ODAsImV4cCI6MTcxMDcxNTE4MH0.8Sg48hnxmTbqs7nG_JoafC7AwXbHX3jWAPLPJ0Qo7VU'

         ```

        **Example Answer**


        ``` json

        {
            "record_count": "2",
            "records": [
                {
                    "id": 101,
                    "uuid": "bef95ce0-1b93-411f-8eb3-170040f94f96",
                    "value": "gardenadmin@adempiere.io",
                    "name": "GardenAdmin",
                    "description": "GardenAdmin",
                    "avatar": ""
                },
                {
                    "id": 102,
                    "uuid": "7e1a3529-af8d-48c1-b25e-a034f5a47865",
                    "value": "gardenuser@adempiere.io",
                    "name": "GardenUser",
                    "description": "GardenUser",
                    "avatar": ""
                }
            ],
            "next_page_token": ""
        }

         ```

        **Change control**


        | **Version** | date | author | Description of Changes |

        | --- | --- | --- | --- |

        | 1.0 | 15/03/2024 | Ricardo | Initial creation of the document. |
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.25.2
            Date:
              schema:
                type: string
                example: Thu, 07 Mar 2024 14:24:00 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '441'
            Connection:
              schema:
                type: string
                example: keep-alive
            grpc-encoding:
              schema:
                type: string
                example: identity
            grpc-accept-encoding:
              schema:
                type: string
                example: gzip
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '98'
            grpc-status:
              schema:
                type: integer
                example: '0'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Max-Age:
              schema:
                type: integer
                example: '3600'
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                type: object
              example:
                record_count: '2'
                records:
                  - id: 101
                    uuid: bef95ce0-1b93-411f-8eb3-170040f94f96
                    value: gardenadmin@adempiere.io
                    name: GardenAdmin
                    description: GardenAdmin
                    avatar: ''
                  - id: 102
                    uuid: 7e1a3529-af8d-48c1-b25e-a034f5a47865
                    value: gardenuser@adempiere.io
                    name: GardenUser
                    description: GardenUser
                    avatar: ''
                next_page_token: ''