openapi: 3.0.0
info:
  title: Task Management
  version: 1.0.0
servers:
  - url: http://{{host}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /task-management/tasks:
    get:
      tags:
        - default
      summary: list-tasks
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}